export const PATHS = Object.freeze({
  home: '/',
  shop: '/shop',
  category: (slug) => `/shop/${slug}`,
  product: (slug) => `/product/${slug}`,
  search: '/search',
  cart: '/cart',
  wishlist: '/wishlist',
  checkout: '/checkout',
  checkoutAddress: '/checkout/address',
  checkoutPayment: '/checkout/payment',
  checkoutReview: '/checkout/review',
  orderConfirmation: (id) => `/order/confirmation/${id}`,
  auth: {
    login: '/login',
    register: '/register',
    forgot: '/forgot-password',
    reset: '/reset-password',
  },
  account: {
    root: '/account',
    profile: '/account/profile',
    orders: '/account/orders',
    orderDetail: (id) => `/account/orders/${id}`,
    addresses: '/account/addresses',
    wishlist: '/account/wishlist',
    password: '/account/password',
    preferences: '/account/preferences',
  },
  about: '/about',
  contact: '/contact',
  faq: '/faq',
  privacy: '/privacy',
  terms: '/terms',
  shippingReturns: '/shipping-returns',
  admin: {
    root: '/admin',
    login: '/admin/login',
    dashboard: '/admin',
    products: '/admin/products',
    productNew: '/admin/products/new',
    productEdit: (id) => `/admin/products/${id}`,
    categories: '/admin/categories',
    inventory: '/admin/inventory',
    orders: '/admin/orders',
    orderDetail: (id) => `/admin/orders/${id}`,
    customers: '/admin/customers',
    customerDetail: (id) => `/admin/customers/${id}`,
    reviews: '/admin/reviews',
    coupons: '/admin/coupons',
    settings: '/admin/settings',
    reports: '/admin/reports',
    users: '/admin/users',
  },
  notFound: '*',
});

export default PATHS;
